version: '3'

services:
  db:
    image: postgres
  docker:
    image: "mirandamoon/django:latest"
    container_name: docker
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/mycode
    ports:
      - "8000:8000"
    depends_on:
      - db
