version: '3'

services:
  web:
    restart: always
    image: "mirandamoon/django:latest"
    container_name: web
    build: .
    volumes:
      - .:/mycodes
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    restart: always
    image: postgres:9.5.4
    build: .
    ports:
      - 5432:5432
    volumes:
      - .:/mycodes
