version: '3'

services:
  postgres:
    restart: always
    image: postgres
  web:
    restart: always
    image: "mirandamoon/django:latest"
    container_name: web
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000" # Change is here <<<<
    volumes:
      - .:/mycodes
    ports:
      - "8000:8000"
    depends_on:
      - postgres
